/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ErrorPage {
        "code": any;
        "path": any;
    }
}
declare global {
    interface HTMLErrorPageElement extends Components.ErrorPage, HTMLStencilElement {
    }
    var HTMLErrorPageElement: {
        prototype: HTMLErrorPageElement;
        new (): HTMLErrorPageElement;
    };
    interface HTMLElementTagNameMap {
        "error-page": HTMLErrorPageElement;
    }
}
declare namespace LocalJSX {
    interface ErrorPage {
        "code"?: any;
        "path"?: any;
    }
    interface IntrinsicElements {
        "error-page": ErrorPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "error-page": LocalJSX.ErrorPage & JSXBase.HTMLAttributes<HTMLErrorPageElement>;
        }
    }
}
